spring.application.name=Attendane
spring.datasource.url=jdbc:mysql://localhost:3306/attendance_db
spring.datasource.username=root
spring.datasource.password=phsyco2003
spring.jpa.hibernate.ddl-auto=update
